### ISSUE TITLE
What affect does this parameter updated_since have on the resutls shown?

### ISSUE THREAD

**Issue by Levi-Armstrong** [change-metrics/monocle#273]
I am interested to know how this parameter affects the results be presented? I have changed it a little but was unable to visually see an affect.

**Comment by morucci** [comment]
It affects the queries sent to the GitHub API to retrieve the PRs. The crawler will fetch the PRs updated since the specified date. But due to how the GitHub API is designed and how we query it, the crawler checks first the PRs database to see the latest PRs indexed and will ignore updated_since if the latest is more recent than the date. That's why you don't see any changes.

If you want to get the full PRs history then my advice is to drop the data you have in the db and set updated_since to 2000-01-01, this way you'll be pretty sure to get the full PRs history.

To do so:
# stop the services
docker-compose stop
# Wipe the index <index-name>
docker-compose run --no-deps crawler /usr/local/bin/monocle \
--elastic-conn elastic:9200 dbmanage --index <index-name> --delete-repository ".*"

Then change the config file to update update_since and finnaly restart the compose.

**Comment by Levi-Armstrong** [comment]
Thank you for the information.
