### ISSUE TITLE
disk usage exceeded flood-stage watermark

### ISSUE THREAD

**Issue by palminha** [change-metrics/monocle#317]
I'm trying to extract data from my company repository in GitHub.

If i use the following parameter `updated_since: "2021-01-01"` in `config.yml` it all works ok.

If I try to get 1 year of PR (using `updated_since: "2020-01-01"`) i get the following error:
`elasticsearch.exceptions.TransportError: TransportError(429, 'cluster_block_exception', 'index [monocle.changes.landing-webapp] blocked by: [TOO_MANY_REQUESTS/12/disk usage exceeded flood-stage watermark, index has read-only-allow-delete block];')`

**Comment by palminha** [comment]
message not clear of what's happening

**Comment by morucci** [comment]
Hi Carlos,

It seems to be due to your disk remaining space. If it is less than 10%
free space then elastic lock it's indices.

You should recover some space, then unlock the indices and finally
docker-compose restart.

See
https://techoverflow.net/2019/04/17/how-to-fix-elasticsearch-forbidden-12-index-read-only-allow-delete-api/


Le mer. 10 mars 2021 à 00:31, Carlos Palminha <notifications@github.com> a
écrit :

**Comment by morucci** [comment]
Hi Carlos,

I agree the message is not clear, but this is related to ElasticSearch as
Monocle uses ElasticSearch for DB backend.
See https://github.com/elastic/elasticsearch/issues/58376

Le mer. 10 mars 2021 à 09:31, Carlos Palminha <notifications@github.com> a
écrit :
