### ISSUE TITLE
Add support for hidding change

### ISSUE THREAD

**Issue by TristanCacqueray** [change-metrics/monocle#728]
When browsing the boards periodically, it might be good to be able to hide a change until it is updated:

- [ ] Add a browser local storage to store the hidden change list (and their last updated time)
- [ ] Add a `hide` button to the change widget
- [ ] Update the boards and change list to hide change (and display a reveal button when changes are hidden).

**Comment by morucci** [comment]
Relates to https://github.com/change-metrics/monocle/issues/663

**Comment by morucci** [comment]
Awesome !  :clap:
However I think that using the setting page to give ability to un-hide hidden changes is not user friendly.
I would like to propose to have a switch icon in the board and changes views called "reveal hidden changes" and when displaying changes (and reveal is set) then hidden changes appears as usual but get an un-hide icon instead of the hide icon.
We could keep the setting page code and have the icon hided for now until it serve real purpose.
